name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: 'read'
  id-token: 'write' # required for Workload Identity; not used here but ok

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR
        run: mvn -B -DskipTests package

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Deploy to Cloud Run
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          SERVICE: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
        run: |
          echo "Deploying $IMAGE to Cloud Run service $SERVICE"
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --platform managed \
            --region "${{ secrets.GCP_REGION }}" \
            --allow-unauthenticated \
            --set-env-vars "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }},SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }},SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}"

      - name: Confirm service URL
        run: |
          gcloud run services describe "${{ secrets.CLOUD_RUN_SERVICE_NAME }}" --region "${{ secrets.GCP_REGION }}" --format="value(status.url)"
